In [ ]:
import pandas as pd
import numpy as np
import csv

In [ ]:
imdb_df = pd.read_csv('imdb_data.csv')

In [ ]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
#columns which are not null
column_to_keep = ['budget','genres','original_language','original_title','cast','crew','revenue']

In [ ]:
imdb_df.loc[~imdb_df['genres'].isna(),'genres']

0                          [{'id': 35, 'name': 'Comedy'}]
1       [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                           [{'id': 18, 'name': 'Drama'}]
3       [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4       [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
                              ...
2995    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996    [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997    [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999    [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...
Name: genres, Length: 2993, dtype: object

In [ ]:
type(imdb_df.loc[0,'cast'])

str

In [ ]:
#converting only non null string
def convert_to_list(str):
  return eval(str)

In [ ]:
#apply the above function only on null values in genres column
imdb_df.loc[~imdb_df['genres'].isna(),'genres'] = imdb_df.loc[~imdb_df['genres'].isna(),'genres'].apply(convert_to_list)

In [ ]:
#apply the above function only on null values in cast column

imdb_df.loc[~imdb_df['cast'].isna(),'cast'] = imdb_df.loc[~imdb_df['cast'].isna(),'cast'].apply(convert_to_list)

In [ ]:
#apply the above function only on null values in crew column
imdb_df.loc[~imdb_df['crew'].isna(),'crew'] = imdb_df.loc[~imdb_df['crew'].isna(),'crew'].apply(convert_to_list)

In [ ]:
#create a copy of original df
imdb_df_new = imdb_df.copy()

In [ ]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
#Q1.Which movie made the highest profit? Who were its producer and director? Identify
#the actors in that film.
imdb_df_new['profit'] = imdb_df_new['revenue'] - imdb_df_new['budget']

In [ ]:
crew = imdb_df_new[imdb_df_new['profit'] == imdb_df_new['profit'].max()][['original_title','crew']]

In [ ]:
# movie which has max profit
print(crew['original_title'])

1761    Furious 7
Name: original_title, dtype: object

In [ ]:
# Producers name which movie name has max profit
print('The Producers are:')
for memebers in crew['crew']:
  for member in memebers:
    if member['job'] == 'Producer':
      print(member['name'])

The Producers are:
Vin Diesel
Neal H. Moritz
Michael Fottrell
Brandon Birtell

In [ ]:
# Director name which movie has max profit
for memebers in crew['crew']:
  for member in memebers:
    if member['job'] == 'Director':
      print('The Director of movie is:',member['name'])

The Director of movie is: James Wan

In [ ]:
cast = imdb_df_new[imdb_df_new['profit'] == imdb_df_new['profit'].max()]['cast']

In [ ]:
for members in cast:
  for member in members:
    print(f"Name: {member['name']} | Character: {member['character']}")

Name: Vin Diesel | Character: Dominic Toretto
Name: Paul Walker | Character: Brian O'Conner
Name: Dwayne Johnson | Character: Hobbs
Name: Michelle Rodriguez | Character: Letty
Name: Tyrese Gibson | Character: Roman
Name: Ludacris | Character: Tej (as Chris 'Ludacris' Bridges)
Name: Jordana Brewster | Character: Mia
Name: Djimon Hounsou | Character: Jakande
Name: Tony Jaa | Character: Kiet
Name: Ronda Rousey | Character: Kara
Name: Nathalie Emmanuel | Character: Ramsey
Name: Kurt Russell | Character: Mr. Nobody
Name: Jason Statham | Character: Deckard Shaw
Name: Sung Kang | Character: Han
Name: Gal Gadot | Character: Gisele
Name: Lucas Black | Character: Sean Boswell
Name: Elsa Pataky | Character: Elena
Name: Noel Gugliemi | Character: Hector
Name: John Brotherton | Character: Sheppard
Name: Luke Evans | Character: Owen Shaw
Name: Ali Fazal | Character: Safar
Name: Miller Kimsey | Character: Jack
Name: Charlie Kimsey | Character: Jack
Name: Eden Estrella | Character: Samantha Hobbs
Name: Gentry White | Character: Letty Fan
Name: Iggy Azalea | Character: Female Racer
Name: Jon Lee Brody | Character: Male Racer
Name: Levy Tran | Character: Race Starter
Name: Anna Colwell | Character: Hot Teacher
Name: Viktor Hernandez | Character: Doctor
Name: Steve Coulter | Character: Priest
Name: Robert Pralgo | Character: Merc Tech
Name: Antwan Mills | Character: Weapons Tech
Name: J.J. Phillips | Character: Billionaire
Name: Jorge Ferragut | Character: Dominican Priest
Name: Sara Sohn | Character: Hana
Name: Benjamin Blankenship | Character: Merc Driver (as Ben Blankenship)
Name: D.J. Hapa | Character: DJ
Name: T-Pain | Character: DJ
Name: Brian Mahoney | Character: Drone Tech
Name: Brittney Alger | Character: Jasmine
Name: Romeo Santos | Character: Mando
Name: Jocelin Donahue | Character: Advisor
Name: Stephanie Langston | Character: Field Reporter
Name: Jorge-Luis Pallo | Character: Cop
Name: Tego Calder√≥n | Character: Leo (uncredited / archive)
Name: Nathalie Kelley | Character: Neela (uncredited / archive)
Name: Shad Moss | Character: Twinkie (uncredited)
Name: Don Omar | Character: Santos (uncredited / archive)
Name: Klement Tinaj | Character: Race Wars Racer (uncredited)
Name: Caleb Walker | Character: Brian O'Conner (uncredited)
Name: Cody Walker | Character: Brian O'Connor (uncredited)

In [ ]:
#Q2.This data has information about movies made in different languages. Which
#language has the highest average ROI (return on investment)?


#calculate roi
imdb_df_new['ROI'] = imdb_df_new['profit']/imdb_df_new['budget'] * 100
#Use groupby function on movie languages and ROI and finding mean
imdb_df_new. groupby ( 'original_language')['ROI'].mean().reset_index().sort_values(by="ROI",ascending=False).head(1)

  original_language  ROI
0                ar  inf

In [ ]:
#Q3.Find out the unique genres of movies in this dataset.
unique_genre = set()
for data in imdb_df_new['genres']:
  # Check if data is iterable before proceeding
  if isinstance(data, (list, tuple)):
    for genre in data:
      if isinstance(genre, dict) and 'name' in genre:
        unique_genre.add(genre['name'])

In [ ]:
unique_genre

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [ ]:
imdb_df_new.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'profit', 'ROI'],
      dtype='object')

In [ ]:
#Q4.Make a table of all the producers and directors of each movie. Find the top 3
#producers who have produced movies with the highest average Rol?

no_na_crew = imdb_df_new[~imdb_df_new['crew'].isna()]

In [ ]:
#A simple function to extract list of all producers for a given movie_index
def create_producer_list(index):
  movie_index = no_na_crew. iloc[index]
  crew_list= movie_index.loc[ 'crew']
  producer_list=[]
  for elem in crew_list:
    if elem['job']=="Producer":
      producer_list.append(elem[ 'name'])
  return producer_list
create_producer_list(61)

['James Hill']

In [ ]:
#A simple function to extract names of all directors for a given movie_index
#each movie has only one director
def create_director (index):
  movie_index = no_na_crew.iloc[index]
  crew_list= movie_index.loc["crew"]
  for elem in crew_list:
    if elem['job'] == 'Director':
      return elem['name']

create_director(61)

'Carol Reed'

In [ ]:
#create a empty DataFrame with required Column names in which we will append data later
Table = pd.DataFrame(columns=['Movie Title','Producers','Directors’, ROI'])

In [ ]:
data_list = []  # Temporary list to store rows before converting to DataFrame

for index, row in no_na_crew.iterrows():
    try:
        data_list.append({
            'Movie Title': no_na_crew.loc[index, 'original_title'],
            'Producers': create_producer_list(index),
            'Directors': create_director(index),
            'ROI': row['ROI']
        })
    except:
        continue

# Convert the list into a DataFrame and assign it to Table
Table = pd.DataFrame(data_list)

NameError: name 'no_na_crew' is not defined

In [ ]:
Table.head(10)

,Movie Title,Producers,Directors,ROI
0,Hot Tub Time Machine 2,[Andrew Panay],Steve Pink,-12.038207
1,The Princess Diaries 2: Royal Engagement,"[Whitney Houston, Mario Iscovich, Debra Martin...",Garry Marshall,137.873588
2,Whiplash,"[David Lancaster, Michel Litvak, Jason Blum, H...",Damien Chazelle,296.727273
3,Kahaani,[Sujoy Ghosh],Sujoy Ghosh,1233.333333
4,마린보이,[],Jong-seok Yoon,inf
5,Pinocchio and the Emperor of the Night,[],Hal Sutherland,-59.229525
6,The Possession,[],Ole Bornedal,510.329107
7,Control Room,[],Jehane Noujaim,inf
8,Muppet Treasure Island,"[Frank Oz, Brian Henson]",Brian Henson,inf
9,A Mighty Wind,[Karen Murphy],Christopher Guest,212.504100

In [ ]:
#Q5.Which actor has acted in the most number of movies? Deep dive into the movies,
#genres and profits corresponding to this actor.


#considering only those rows in cast column which have no null values
no_na_cast = imdb_df_new[~imdb_df_new[ 'cast'].isna()]
no_na_cast.loc[0, 'cast'][0]['name']

'Rob Corddry'

In [ ]:
actor_list = []
for index,row in no_na_cast.iterrows():
  for iter in no_na_cast.loc[index, 'cast']:
    if type(iter) == dict:
      actor= iter['name']
      actor_list.append(actor)

In [ ]:
#create a DataFrame with actor list
Actor_Table = pd.DataFrame(actor_list,columns = ['Name of Actor'])

In [ ]:
Actor_Table.shape

(61811, 1)

In [ ]:
Actor_Table.head()

    Name of Actor
0     Rob Corddry
1  Craig Robinson
2      Clark Duke
3      Adam Scott
4     Chevy Chase

In [ ]:
#sorting the actors using groupby function
Actor_Table.value_counts().reset_index().head()

       Name of Actor  count
0  Samuel L. Jackson     30
1     Robert De Niro     30
2     Morgan Freeman     27
3        Liam Neeson     25
4     Susan Sarandon     25

In [ ]:
print('Sanuel L. Jackson and Robert De Niro both have done 3@ films')

Sanuel L. Jackson and Robert De Niro both have done 3@ films

In [ ]:
profit1 = []
profit2 = []
movie1 = []
movie2 = []
for index,row in no_na_cast.iterrows():
  for iter in no_na_cast.loc[index, 'cast']:
    if type(iter) == dict:
      actor= iter['name']
      if 'Robert De Niro' in actor:
        profit1.append(no_na_cast.loc[index, 'profit'])
        movie1.append(no_na_cast.loc[index, 'original_title'])



      if 'Samuel L. Jackson' in actor:
        profit2.append(no_na_cast.loc[index, 'profit'])
        movie2.append(no_na_cast.loc[index, 'original_title'])

In [ ]:
gener_r = []
for i in range(len(movie1)):
    a = [g['name'] for g in no_na_cast.loc[i, 'genres']]
    gener_r.append(a)

gener_s = []
for i in range(len(movie2)):
    b = [g['name'] for g in no_na_cast.loc[i, 'genres']]
    gener_s.append(b)

In [ ]:
genr = np.array(gener_r, dtype=object)
gens = np.array(gener_s, dtype=object)

In [ ]:
#creating sub dataframe for Robert
mov1= pd.DataFrame(movie1,columns=[ "Movie Name"])
prof1=pd.DataFrame(profit1,columns=[ 'Movie Profit'])
gen1= pd.DataFrame(genr.flatten(),columns=[ 'Genres'])


Movies_by_Robert=pd.concat([mov1,gen1,prof1],axis=1)

In [ ]:
Movies_by_Robert.sort_values(by="Movie Profit",ascending=False).head()

          Movie Name                                      Genres  Movie Profit
8   Meet the Parents  [Action, Comedy, Music, Family, Adventure]     275444045
16   American Hustle                          [Horror, Thriller]     211171807
10          Sleepers                                     [Drama]     121615285
26      Analyze This           [Crime, Drama, Mystery, Thriller]      96885658
29         Backdraft        [Action, Adventure, Crime, Thriller]      77368585

In [ ]:
#creating sub dataframe for Samuel
mov2= pd.DataFrame(movie2,columns=[ "Movie Name"])
prof2=pd.DataFrame(profit2,columns=[ 'Movie Profit'])
gen2= pd.DataFrame(gens.flatten(),columns=[ 'Genres'])


Movies_by_Samuel=pd.concat([mov2,gen2,prof2],axis=1)


Movies_by_Samuel.sort_values(by="Movie Profit",ascending=False).head()

,Movie Name,Genres,Movie Profit
5,The Avengers,"[Animation, Adventure, Family]",1299557910
24,Avengers: Age of Ultron,"[Horror, Comedy]",1125403694
11,Jurassic Park,[Comedy],857100000
3,Star Wars: Episode III - Revenge of the Sith,"[Thriller, Drama]",737000000
15,Captain America: The Winter Soldier,"[Action, Crime, Drama]",544766572